/**
 * Human-facing sequence number formatting (PO numbers, GRN numbers).
 * The numeric sequence itself is generated by the caller (typically from a
 * database sequence/count within the same transaction as the row insert,
 * to avoid collisions) - this module only formats it consistently.
 */
export function formatSequenceNumber(prefix: string, year: number, sequence: number): string {
  const padded = String(sequence).padStart(6, '0');
  return `${prefix}-${year}-${padded}`;
}
