// Preview catalogue for the local demo (LR-010): the approved launch
// assortment (scripts/demo-data/aistudio-catalogue.json, generated by
// scripts/generate-launch-assortment.mjs from the Product Owner's
// 2026-10-04 approved Men/Women assortment) loaded through the real staff
// API - the same paths an operator uses - so the demo shows the approved
// products, prices, colours and attributes on the real backend.
//
// Prisma is used only for reference data with no staff route (categories,
// sizes, SKU size-chart links). Not copied into this file: reviews,
// ratings, view counts and likes (never invented, LR-001). Every image is
// a neutral placeholder under /placeholders (image generation is paused;
// see CLAUDE.md) - never a real or implied product photograph.
//
//   DEMO_SEED_ALLOWED=preview DEMO_API_URL=http://localhost:4000 DATABASE_URL=... \
//   SEED_SUPER_ADMIN_EMAIL=... SEED_SUPER_ADMIN_PASSWORD=... node scripts/seed-demo.mjs
//
// Re-running is safe: existing demo styles (style code prefix VNY-LA-),
// collections, media and banners are left as they are. Bumping the
// catalogue's "version" field makes `npm run demo` rebuild the demo
// database from scratch, which is what actually removes the previous
// (festive/ethnicwear) assortment - this file has no separate "archive
// the old catalogue" step because nothing of it survives a version bump.
import { readFileSync } from 'node:fs';
import { PrismaClient } from '@fcp/db';

// A preview runs as NODE_ENV=production with DEPLOYMENT_STAGE=preview
// (LR-010); the real production stage is always refused.
const productionStage = process.env.NODE_ENV === 'production' && process.env.DEPLOYMENT_STAGE !== 'preview';
if (process.env.DEMO_SEED_ALLOWED !== 'preview' || productionStage) {
  throw new Error('Demo data is for preview environments only. Set DEMO_SEED_ALLOWED=preview (never in production).');
}
const API = `${process.env.DEMO_API_URL ?? 'http://localhost:4000'}/api/v1`;
const { version: CATALOGUE_VERSION, products: PRODUCTS, reels: REELS } = JSON.parse(readFileSync(new URL('./demo-data/aistudio-catalogue.json', import.meta.url), 'utf8'));
const prisma = new PrismaClient();

async function call(method, path, body, token, attempt = 0) {
  const res = await fetch(`${API}${path}`, {
    method,
    headers: { ...(body ? { 'content-type': 'application/json' } : {}), ...(token ? { authorization: `Bearer ${token}` } : {}) },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });
  const text = await res.text();
  // The catalogue is loaded through the real staff API, which rate-limits
  // writes; wait out the window instead of failing the demo start.
  if (res.status === 429 && attempt < 10) {
    const seconds = Number(res.headers.get('retry-after')) || Number(/retry in (\d+)/.exec(text)?.[1]) || 5;
    await new Promise((resolve) => setTimeout(resolve, (seconds + 1) * 1000));
    return call(method, path, body, token, attempt + 1);
  }
  if (res.status >= 300) throw new Error(`${method} ${path} -> ${res.status} ${text.slice(0, 300)}`);
  return text ? JSON.parse(text) : null;
}

const slugify = (value) => value.toLowerCase().replace(/&/g, ' ').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
// Media/banner URLs must be absolute (the staff API validates with
// z.string().url()) - these are served by the storefront's own
// /public/placeholders directory.
const STOREFRONT_URL = process.env.DEMO_STOREFRONT_URL ?? 'http://localhost:3000';
const placeholder = (file) => `${STOREFRONT_URL}/placeholders/${file}`;

// Every category the approved launch assortment and navigation use (Men:
// daily wear/premium shirts/business casual; Women: daily/work/casual/
// partywear - no ethnicwear/ceremonial/wedding for men, no sarees/
// lehengas/bridalwear/festive ethnicwear for women).
const CATEGORY_NAMES = [...new Set(PRODUCTS.map((p) => p.category))];
const SIZE_ORDER = [
  'XS', 'S', 'M', 'L', 'XL', 'XXL',
  'UK6', 'UK7', 'UK8', 'UK9', 'UK10', 'UK11',
  '32', '34', '36', '38', '40',
  '50ml', '100ml',
];

// Tax (GST/HSN): apparel, footwear, leather goods and fragrance sit on
// different HSN headings and rates. Demo values only - not a verified
// registration or a verified rate (TAX-001..005 stay open).
const HSN_BY_PRODUCT_TYPE = {
  apparel: { hsnCode: '6211', gstRatePercent: 12 },
  footwear: { hsnCode: '6403', gstRatePercent: 18 },
  belt: { hsnCode: '4203', gstRatePercent: 18 },
  fragrance: { hsnCode: '3303', gstRatePercent: 18 },
};
// The design's size guide tables (SizeGuideModal.tsx), as size charts.
const CHARTS = {
  women: {
    name: 'Women · garment sizing and fit guide',
    entries: [['XS', 32, 26, 36, 14], ['S', 34, 28, 38, 14.5], ['M', 36, 30, 40, 15], ['L', 38, 32, 42, 15.5], ['XL', 40, 34, 44, 16], ['XXL', 42, 36, 46, 16.5]]
      .map(([sizeLabel, bustIn, waistIn, hipIn, shoulderIn]) => [sizeLabel, { bustIn, waistIn, hipIn, shoulderIn }]),
  },
  men: {
    name: 'Men · garment sizing and fit guide',
    entries: [['S', 38, '30-32', 38, 17], ['M', 40, '32-34', 40, 17.5], ['L', 42, '34-36', 42, 18], ['XL', 44, '36-38', 44, 18.5], ['XXL', 46, '38-40', 46, 19]]
      .map(([sizeLabel, chestIn, waistIn, hipIn, shoulderIn]) => [sizeLabel, { chestIn, waistIn, hipIn, shoulderIn }]),
  },
};
const BADGES = { BESTSELLER: 'BESTSELLER', NEW: 'NEW_ARRIVAL' };

// Editorial placements as CMS banners (placement per department; the
// storefront reads them - see bridge/editorial.ts). Every image is a
// neutral placeholder (image generation is paused; the approved models
// for the next stage are Aryan, Heena, Riya, Deeksha and Alisha - none of
// this demo content is their photography). Links point at the new
// launch-assortment categories/collections, never the retired festive
// ones.
const BANNERS = {
  men: {
    gateway: [['Modern Indian Menswear · Daily Wear & Business Casual', placeholder('gateway-men.svg'), '/']],
    'home-hero': [['Business Casual, Done Right', placeholder('hero-men.svg'), '/category/men']],
    'home-feature': [['Premium Shirts for Every Workday', placeholder('category-tile.svg'), '/collections/premium-shirts']],
    'home-category': [
      ['FORMAL SHIRTS', placeholder('category-tile.svg'), '/category/formal-shirts'],
      ['CASUAL SHIRTS', placeholder('category-tile.svg'), '/category/casual-shirts'],
      ['POLO T-SHIRTS', placeholder('category-tile.svg'), '/category/polo-t-shirts'],
      ['DENIMS', placeholder('category-tile.svg'), '/category/denims'],
      ['CHINOS', placeholder('category-tile.svg'), '/category/casual-trousers-chinos'],
      ['FORMAL TROUSERS', placeholder('category-tile.svg'), '/category/formal-trousers'],
      ['SHOES', placeholder('category-tile.svg'), '/category/business-casual-shoes'],
      ['BELTS', placeholder('category-tile.svg'), '/category/business-casual-belts'],
    ],
    'home-occasion': [
      ['For the Workday', placeholder('lifestyle.svg'), '/collections/workday'],
      ['Everyday Essentials', placeholder('lifestyle.svg'), '/collections/everyday'],
      ['Business Casual Edit', placeholder('lifestyle.svg'), '/collections/business-casual'],
    ],
    'home-tastemakers': [
      ['Business Casual Shirting', placeholder('lifestyle.svg')],
      ['Everyday Polos', placeholder('lifestyle.svg')],
      ['Weekend Denim', placeholder('lifestyle.svg')],
      ['Workday Trousers', placeholder('lifestyle.svg')],
    ],
  },
  women: {
    gateway: [['Modern Indian Womenswear · Daily, Work & Partywear', placeholder('gateway-women.svg'), '/']],
    'home-hero': [['Workwear to Weekend to Evening', placeholder('hero-women.svg'), '/category/women']],
    'home-feature': [['Everyday Kurtis, Reimagined', placeholder('category-tile.svg'), '/category/everyday-kurtis']],
    'home-category': [
      ['TOPS', placeholder('category-tile.svg'), '/category/tops'],
      ['TEES', placeholder('category-tile.svg'), '/category/tees'],
      ['EVERYDAY KURTIS', placeholder('category-tile.svg'), '/category/everyday-kurtis'],
      ['DENIMS', placeholder('category-tile.svg'), '/category/denims'],
      ['DRESSES', placeholder('category-tile.svg'), '/category/dresses'],
      ['TROUSERS', placeholder('category-tile.svg'), '/category/trousers'],
      ['SKIRTS', placeholder('category-tile.svg'), '/category/skirts'],
      ['PARTY & EVENING', placeholder('category-tile.svg'), '/collections/party-evening'],
    ],
    'home-occasion': [
      ['Workwear', placeholder('lifestyle.svg'), '/collections/workwear'],
      ['Weekend', placeholder('lifestyle.svg'), '/collections/weekend'],
      ['Party & Evening', placeholder('lifestyle.svg'), '/collections/party-evening'],
    ],
    'home-tastemakers': [
      ['Workwear Edit', placeholder('lifestyle.svg')],
      ['Everyday Kurtis', placeholder('lifestyle.svg')],
      ['Weekend Denim', placeholder('lifestyle.svg')],
      ['Party & Evening', placeholder('lifestyle.svg')],
    ],
  },
};

const { token } = await call('POST', '/auth/staff/login', { email: process.env.SEED_SUPER_ADMIN_EMAIL, password: process.env.SEED_SUPER_ADMIN_PASSWORD });
const yesterday = new Date(Date.now() - 86_400_000).toISOString();
const summary = { catalogue: CATALOGUE_VERSION, created: 0, skipped: 0 };

// --- Reference data ---
const categories = {};
for (const name of CATEGORY_NAMES) {
  const slug = slugify(name);
  categories[name] = await prisma.category.upsert({ where: { slug }, update: { name, isActive: true }, create: { slug, name } });
}
const sizes = {};
for (const [index, label] of SIZE_ORDER.entries()) sizes[label] = await prisma.size.upsert({ where: { label }, update: { sortOrder: index + 1 }, create: { label, sortOrder: index + 1 } });

let brand = await prisma.brand.findFirst({ where: { code: 'VANYA' } });
if (!brand) brand = await call('POST', '/organization/brands', { code: 'VANYA', name: 'VANYA' }, token);
let location = await prisma.location.findFirst({ where: { code: 'VNY-DEMO-WH' } });
if (!location) {
  location = await call('POST', '/organization/locations', { code: 'VNY-DEMO-WH', name: 'VANYA Demo Warehouse', type: 'WAREHOUSE' }, token);
  // Checkout sells only from a GST-configured location (M08). DEMO values only:
  // not a verified registration or a verified rate (TAX-001..005 stay open).
  const entity = await call('POST', '/tax/legal-entities', { legalName: 'VANYA Demo (not a real entity)', registeredState: 'Delhi' }, token);
  const gst = await call('POST', '/tax/gst-registrations', { legalEntityId: entity.id, gstin: 'DLDEMO00001A1Z5', stateCode: 'DL', stateName: 'Delhi', status: 'ACTIVE', effectiveFrom: yesterday }, token);
  await call('POST', `/tax/locations/${location.id}/gst-registration`, { gstRegistrationId: gst.id }, token);
  for (const { hsnCode, gstRatePercent } of Object.values(HSN_BY_PRODUCT_TYPE)) {
    await call('POST', '/tax/rates', { hsnCode, gstRatePercent, effectiveFrom: yesterday }, token).catch(() => undefined);
  }
}
for (const [pincode, city, state] of [['110001', 'New Delhi', 'Delhi'], ['400001', 'Mumbai', 'Maharashtra'], ['560001', 'Bengaluru', 'Karnataka'], ['600001', 'Chennai', 'Tamil Nadu'], ['700001', 'Kolkata', 'West Bengal']]) {
  await call('POST', '/pdp/pincodes', { pincode, city, state, isServiceable: true, codAvailable: true }, token).catch(() => undefined);
}

const charts = {};
for (const [gender, chart] of Object.entries(CHARTS)) {
  charts[gender] = await prisma.sizeChart.findFirst({ where: { name: chart.name } })
    ?? await call('POST', '/products/size-charts', { name: chart.name, gender, brandId: brand.id, entries: chart.entries.map(([sizeLabel, measurements]) => ({ sizeLabel, measurements })) }, token);
}
const chartLabels = Object.fromEntries(Object.entries(CHARTS).map(([gender, chart]) => [gender, new Set(chart.entries.map(([label]) => label))]));

// --- Styles ---
const styleIds = {};
for (const p of PRODUCTS) {
  const styleCode = `VNY-LA-${p.id.toUpperCase()}`;
  const existing = await prisma.style.findFirst({ where: { styleCode } });
  if (existing) { styleIds[p.id] = existing.id; summary.skipped += 1; continue; }
  const { hsnCode } = HSN_BY_PRODUCT_TYPE[p.productType] ?? HSN_BY_PRODUCT_TYPE.apparel;
  const style = await call('POST', '/products/styles', {
    styleCode, name: p.title, brandId: brand.id, categoryId: categories[p.category].id,
    season: 'Core 2026', collection: p.collection,
    department: p.gender === 'men' ? 'Menswear' : 'Womenswear', gender: p.gender,
    fabric: p.fabric, fit: p.fit, occasion: p.occasion, washCare: p.care.join('. '),
    countryOfOrigin: 'India', hsnCode,
    customAttributes: { subtitle: p.subtitle, details: p.details, productType: p.productType, ...p.customAttributes },
  }, token);
  styleIds[p.id] = style.id;
  const colourRows = [];
  for (const [index, colour] of p.colors.entries()) {
    colourRows.push(await call('POST', `/products/styles/${style.id}/colours`, { name: colour.name, colourCode: `C${index + 1}`, hexSwatch: colour.hex }, token));
  }
  const skus = await call('POST', `/products/styles/${style.id}/skus/generate`, { sizeIds: p.sizes.map((s) => sizes[s.size].id) }, token);
  if (p.sizes.every((s) => chartLabels[p.gender]?.has(s.size))) {
    await prisma.sku.updateMany({ where: { styleId: style.id }, data: { sizeChartId: charts[p.gender].id } });
  }
  let sortOrder = 0;
  for (const [index, colour] of p.colors.entries()) {
    for (const url of colour.images) {
      await call('POST', `/products/styles/${style.id}/media`, {
        colourId: colourRows[index].id, url, sortOrder: sortOrder++,
        altText: `${p.title} in ${colour.name} (placeholder image)`,
      }, token);
    }
  }
  await call('POST', '/catalog/prices', { styleId: style.id, mrp: p.mrp, sellingPrice: p.price }, token);
  for (const sku of skus) {
    const size = p.sizes.find((s) => sizes[s.size].id === sku.sizeId);
    const quantity = size?.inStock ? (size.stockCount ?? 10) : 0;
    if (quantity > 0) await call('POST', '/inventory/adjustments', { skuId: sku.skuId, locationId: location.id, quantityDelta: quantity, reason: 'Demo opening stock', idempotencyKey: `demo-stock-${sku.skuId}` }, token);
  }
  for (const step of ['ready-for-enrichment', 'qa-check', 'publish']) await call('POST', `/products/styles/${style.id}/${step}`, undefined, token);
  for (const badge of new Set((p.badges ?? []).map((b) => BADGES[b]).filter(Boolean))) {
    await call('POST', '/catalog/badges', { styleId: style.id, badgeType: badge, source: 'MANUAL' }, token);
  }
  summary.created += 1;
}

// --- Collections (Men: Workday, Everyday, Business Casual, Premium
// Shirts; Women: Everyday, Workwear, Weekend, Party / Evening). A style
// can belong to more than one - "Business Casual" is explicitly a
// cross-category collection spanning suitable men's items on top of
// their own primary collection (e.g. Premium Shirts + Business Casual). ---
const collections = new Map();
for (const p of PRODUCTS) {
  for (const name of [p.collection, ...(p.additionalCollections ?? [])]) {
    collections.set(name, [...(collections.get(name) ?? []), p.id]);
  }
}
for (const [name, members] of collections) {
  const slug = slugify(name);
  if (await prisma.collection.findFirst({ where: { slug } })) { summary.skipped += 1; continue; }
  const collection = await call('POST', '/catalog/collections', { name, slug, description: `${name} from VANYA.` }, token);
  for (const member of members) await call('POST', `/catalog/collections/${collection.id}/styles`, { styleId: styleIds[member] }, token);
  await call('POST', `/catalog/collections/${collection.id}/publish`, undefined, token);
  summary.created += 1;
}

// --- Watch & Shop: the design's reels (internal shoppable media) ---
for (const [index, reel] of REELS.entries()) {
  if (await prisma.shoppableMedia.findFirst({ where: { title: reel.title } })) { summary.skipped += 1; continue; }
  const media = await call('POST', '/content/shoppable-media', {
    title: reel.title, mediaUrl: reel.videoUrl ?? reel.thumbnail, thumbnailUrl: reel.thumbnail,
    creatorAttribution: `${reel.creator.name} · ${reel.creator.handle}`, merchandisingPosition: index,
  }, token);
  for (const [sortOrder, productId] of reel.taggedProductIds.entries()) {
    if (styleIds[productId]) await call('POST', `/content/shoppable-media/${media.id}/tags`, { styleId: styleIds[productId], sortOrder }, token);
  }
  await call('POST', `/content/shoppable-media/${media.id}/transition`, { toState: 'PUBLISHED' }, token);
  summary.created += 1;
}

// --- Editorial imagery (CMS banners) ---
for (const [department, placements] of Object.entries(BANNERS)) {
  for (const [key, banners] of Object.entries(placements)) {
    const placement = `${key}-${department}`;
    if (await prisma.cmsBanner.findFirst({ where: { placement } })) { summary.skipped += 1; continue; }
    for (const [sortOrder, [title, imageUrl, linkUrl]] of banners.entries()) {
      await call('POST', '/cms/banners', { title, imageUrl, ...(linkUrl ? { linkUrl } : {}), placement, sortOrder }, token);
    }
    summary.created += 1;
  }
}

await prisma.$disconnect();
console.log(JSON.stringify(summary, null, 2));
